volumes:
  sock:

services:
  lb:
    build: .
    command: ["/lb"]
    ports:
      - "9999:9999"
    volumes:
      - sock:/run/sock
    networks:
      - fraud-net
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "6MB"

  api1:
    build: .
    environment:
      - SOCK=/run/sock/api1.sock
    volumes:
      - sock:/run/sock
    networks:
      - fraud-net
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: "0.475"
          memory: "172MB"

  api2:
    build: .
    environment:
      - SOCK=/run/sock/api2.sock
    volumes:
      - sock:/run/sock
    networks:
      - fraud-net
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: "0.475"
          memory: "172MB"

networks:
  fraud-net:
    driver: bridge
