volumes:
  sock:

services:
  lb:
    image: haproxy:alpine
    ports:
      - "9999:9999"
    volumes:
      - sock:/run/sock
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - fraud-net
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "14MB"

  api1:
    build: .
    environment:
      - SOCK=/run/sock/api1.sock
    volumes:
      - sock:/run/sock
    networks:
      - fraud-net
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "168MB"

  api2:
    build: .
    environment:
      - SOCK=/run/sock/api2.sock
    volumes:
      - sock:/run/sock
    networks:
      - fraud-net
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "168MB"

networks:
  fraud-net:
    driver: bridge
